In [1]:
# import necerssary libraries

import numpy as np
import pandas as pd

# to build linear model
from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import LabelBinarizer

In [31]:
# to visualization purposes
import matplotlib.pyplot as plt

In [2]:
# load dataset
data = pd.read_csv('new.csv')
data

       Location  Temperature  Rainfall  fillingrate
0    Location 1           27         2            7
1    Location 2           27         2            5
2    Location 3           27         2            8
3    Location 4           27         2            2
4    Location 5           27         2            8
5    Location 6           27         2            7
6    Location 7           27         2            9
7    Location 8           27         2            6
8    Location 9           27         2            5
9   Location 10           27         2            8
10   Location 1           21        30            5
11   Location 2           21        30            1
12   Location 3           21        30            5
13   Location 4           21        30            4
14   Location 5           21        30            2
15   Location 6           21        30            6
16   Location 7           21        30            1
17   Location 8           21        30            4
18   Location 9           21        30            4
19  Location 10           21        30            1
20   Location 1           25        10            6
21   Location 2           25        10            2
22   Location 3           25        10            6
23   Location 4           25        10            4
24   Location 5           25        10            4
25   Location 6           25        10            6
26   Location 7           25        10            2
27   Location 8           25        10            5
28   Location 9           25        10            7
29  Location 10           25        10            2

In [42]:
import statsmodels.formula.api as smf

In [18]:
location = pd.get_dummies(data.Location)

In [19]:
print(location)

    Location 1  Location 10  Location 2  Location 3  Location 4  Location 5  \
0            1            0           0           0           0           0
1            0            0           1           0           0           0
2            0            0           0           1           0           0
3            0            0           0           0           1           0
4            0            0           0           0           0           1
5            0            0           0           0           0           0
6            0            0           0           0           0           0
7            0            0           0           0           0           0
8            0            0           0           0           0           0
9            0            1           0           0           0           0
10           1            0           0           0           0           0
11           0            0           1           0           0           0
12           0            0           0           1           0           0
13           0            0           0           0           1           0
14           0            0           0           0           0           1
15           0            0           0           0           0           0
16           0            0           0           0           0           0
17           0            0           0           0           0           0
18           0            0           0           0           0           0
19           0            1           0           0           0           0
20           1            0           0           0           0           0
21           0            0           1           0           0           0
22           0            0           0           1           0           0
23           0            0           0           0           1           0
24           0            0           0           0           0           1
25           0            0           0           0           0           0
26           0            0           0           0           0           0
27           0            0           0           0           0           0
28           0            0           0           0           0           0
29           0            1           0           0           0           0

    Location 6  Location 7  Location 8  Location 9
0            0           0           0           0
1            0           0           0           0
2            0           0           0           0
3            0           0           0           0
4            0           0           0           0
5            1           0           0           0
6            0           1           0           0
7            0           0           1           0
8            0           0           0           1
9            0           0           0           0
10           0           0           0           0
11           0           0           0           0
12           0           0           0           0
13           0           0           0           0
14           0           0           0           0
15           1           0           0           0
16           0           1           0           0
17           0           0           1           0
18           0           0           0           1
19           0           0           0           0
20           0           0           0           0
21           0           0           0           0
22           0           0           0           0
23           0           0           0           0
24           0           0           0           0
25           1           0           0           0
26           0           1           0           0
27           0           0           1           0
28           0           0           0           1
29           0           0           0           0

In [20]:
data.head

<bound method NDFrame.head of        Location  Temperature  Rainfall  fillingrate
0    Location 1           27         2            7
1    Location 2           27         2            5
2    Location 3           27         2            8
3    Location 4           27         2            2
4    Location 5           27         2            8
5    Location 6           27         2            7
6    Location 7           27         2            9
7    Location 8           27         2            6
8    Location 9           27         2            5
9   Location 10           27         2            8
10   Location 1           21        30            5
11   Location 2           21        30            1
12   Location 3           21        30            5
13   Location 4           21        30            4
14   Location 5           21        30            2
15   Location 6           21        30            6
16   Location 7           21        30            1
17   Location 8           21        30            4
18   Location 9           21        30            4
19  Location 10           21        30            1
20   Location 1           25        10            6
21   Location 2           25        10            2
22   Location 3           25        10            6
23   Location 4           25        10            4
24   Location 5           25        10            4
25   Location 6           25        10            6
26   Location 7           25        10            2
27   Location 8           25        10            5
28   Location 9           25        10            7
29  Location 10           25        10            2>

In [22]:

pd.get_dummies([data,location],axis='columns')

TypeError: get_dummies() got an unexpected keyword argument 'axis'

In [23]:
merged= pd.concat([data,location],axis='columns')

In [24]:
merged

,Location,Temperature,Rainfall,fillingrate,Location 1,Location 10,Location 2,Location 3,Location 4,Location 5,Location 6,Location 7,Location 8,Location 9
0,Location 1,27,2,7,1,0,0,0,0,0,0,0,0,0
1,Location 2,27,2,5,0,0,1,0,0,0,0,0,0,0
2,Location 3,27,2,8,0,0,0,1,0,0,0,0,0,0
3,Location 4,27,2,2,0,0,0,0,1,0,0,0,0,0
4,Location 5,27,2,8,0,0,0,0,0,1,0,0,0,0
5,Location 6,27,2,7,0,0,0,0,0,0,1,0,0,0
6,Location 7,27,2,9,0,0,0,0,0,0,0,1,0,0
7,Location 8,27,2,6,0,0,0,0,0,0,0,0,1,0
8,Location 9,27,2,5,0,0,0,0,0,0,0,0,0,1
9,Location 10,27,2,8,0,1,0,0,0,0,0,0,0,0
10,Location 1,21,30,5,1,0,0,0,0,0,0,0,0,0
11,Location 2,21,30,1,0,0,1,0,0,0,0,0,0,0
12,Location 3,21,30,5,0,0,0,1,0,0,0,0,0,0
13,Location 4,21,30,4,0,0,0,0,1,0,0,0,0,0
14,Location 5,21,30,2,0,0,0,0,0,1,0,0,0,0
15,Location 6,21,30,6,0,0,0,0,0,0,1,0,0,0
16,Location 7,21,30,1,0,0,0,0,0,0,0,1,0,0
17,Location 8,21,30,4,0,0,0,0,0,0,0,0,1,0
18,Location 9,21,30,4,0,0,0,0,0,0,0,0,0,1
19,Location 10,21,30,1,0,1,0,0,0,0,0,0,0,0
20,Location 1,25,10,6,1,0,0,0,0,0,0,0,0,0
21,Location 2,25,10,2,0,0,1,0,0,0,0,0,0,0
22,Location 3,25,10,6,0,0,0,1,0,0,0,0,0,0
23,Location 4,25,10,4,0,0,0,0,1,0,0,0,0,0
24,Location 5,25,10,4,0,0,0,0,0,1,0,0,0,0
25,Location 6,25,10,6,0,0,0,0,0,0,1,0,0,0
26,Location 7,25,10,2,0,0,0,0,0,0,0,1,0,0
27,Location 8,25,10,5,0,0,0,0,0,0,0,0,1,0
28,Location 9,25,10,7,0,0,0,0,0,0,0,0,0,1
29,Location 10,25,10,2,0,1,0,0,0,0,0,0,0,0

In [16]:
data['location']=location

ValueError: Expected a 1D array, got an array with shape (30, 10)

In [25]:
merged.dtypes

Location       object
Temperature     int64
Rainfall        int64
fillingrate     int64
Location 1      uint8
Location 10     uint8
Location 2      uint8
Location 3      uint8
Location 4      uint8
Location 5      uint8
Location 6      uint8
Location 7      uint8
Location 8      uint8
Location 9      uint8
dtype: object

In [26]:
final=merged.drop(['Location'],axis="columns")

In [27]:
# build and train model
model = LinearRegression()
model.fit(final[['Location 1','Location 2','Location 3','Location 4','Location 5','Location 6','Location 7','Location 8','Location 9','Location 10','Temperature', 'Rainfall']], data.fillingrate)

LinearRegression()

In [34]:
# get predictions from model
model.predict([[1,0,0,0,0,0,0,0,0,0,27,2]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.7])

In [33]:
plt.scatter(final.fillingrate, color='red')
plt.xlabel('Location 1','Location 2','Location 3','Location 4','Location 5','Location 6','Location 7','Location 8','Location 9','Location 10','Temperature', 'Rainfall')
plt.ylabel('fillingrate')

TypeError: scatter() missing 1 required positional argument: 'y'